project_id = "kqykfukhtxjpjblsdwmd"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.upload-evidence]
verify_jwt = true

[functions.generate-report]
verify_jwt = true

[functions.create-timestamp]
verify_jwt = true