// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqykfukhtxjpjblsdwmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxeWtmdWtodHhqcGpibHNkd21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzUzOTQsImV4cCI6MjA3NDQxMTM5NH0.vs52UiFVIkAw-ISq4-oKsMjpBAypQYG4kAW8dAFs_QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});